language: minimal
os: linux
git:
  depth: 1
  
stages:
  - compile
  - test
  
env:
  global:
    - scversion=latest
    
jobs:
  include:
  - stage: compile
    name: "Job 1"
    script: echo "HELLO JOB 1" #&& export PATH=$(readlink -f "shellcheck-${scversion}"):$PATH
  - name: "Job 2"
    script:
    - echo "HELLO JOB 2"
    - echo "Trying to multi string"
  - stage: test
    script: 'find . -executable -type f  -not -path "./.git*" -not -path "./shellcheck*" | xargs shellcheck -S style -W 20 -f gcc --color=always'
    
install:
  - wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
  
script:
  - export PATH=$(readlink -f "shellcheck-${scversion}"):$PATH
  - shellcheck --version
  - shellcheck --help || true
  - 'find . -executable -type f  -not -path "./.git*" -not -path "./shellcheck*" | xargs shellcheck -S style -W 20 -f gcc --color=always'
